# Generated by Django 2.1 on 2019-05-28 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplanpaypalbill',
            name='userPlan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datame.UserPlan'),
        ),
    ]
