# Generated by Django 2.2 on 2019-05-24 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('nif', models.CharField(max_length=9, verbose_name='NIF')),
                ('logo', models.URLField(verbose_name='Logo URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DataScientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('photo', models.CharField(max_length=100, verbose_name='Photo')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone', models.CharField(max_length=9, verbose_name='Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Offer title')),
                ('description', models.TextField(max_length=1000, verbose_name='Offer description')),
                ('price_offered', models.FloatField(verbose_name='Price offered')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('limit_time', models.DateTimeField(blank=True)),
                ('finished', models.BooleanField(default=False)),
                ('files', models.URLField()),
                ('contract', models.TextField(max_length=2000, verbose_name='Contract')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datame.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Section_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRO', 'PRO')], max_length=4, verbose_name='Type')),
                ('startDate', models.DateTimeField(null=True)),
                ('expirationDate', models.DateTimeField(null=True)),
                ('isPayed', models.BooleanField(default=False)),
                ('dataScientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datame.DataScientist')),
            ],
        ),
        migrations.CreateModel(
            name='Submition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=100, verbose_name='File')),
                ('comments', models.TextField(max_length=1000, verbose_name='Comments')),
                ('status', models.CharField(choices=[('SU', 'SUBMITTED'), ('AC', 'ACEPTED'), ('RE', 'REJECTED')], max_length=9, verbose_name='Status')),
                ('dataScientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datame.DataScientist')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datame.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='datame.CV')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_name', to='datame.Section_name')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='score')),
                ('comments', models.TextField(max_length=1000, verbose_name='comments')),
                ('reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('body', models.TextField(max_length=1000, verbose_name='body')),
                ('moment', models.DateTimeField(auto_now=True)),
                ('isAlert', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('entity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Entity')),
                ('date_start', models.DateField(verbose_name='Start date')),
                ('date_finish', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='datame.Section')),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='owner',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='datame.DataScientist'),
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Apply title')),
                ('description', models.TextField(max_length=1000, verbose_name='Apply description')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PE', 'PENDING'), ('AC', 'ACEPTED'), ('RE', 'REJECTED')], max_length=8, verbose_name='Status')),
                ('dataScientist', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='datame.DataScientist')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datame.Offer')),
            ],
        ),
    ]
